
Examples = ("The restaurant had amazing food, but the service wasn't that great.",
             "I love going to that place in the evening!",
             "The area is very crowded, but the view is worth it!",
            "The Gourmet Garden has a delightful atmosphere and friendly staff, but the steak was overcooked and the vegetables were underseasoned, making for a mixed experience.",
            "While 'Eclipse of Shadows' features stunning cinematography and a compelling lead actor, the convoluted plot and slow pacing detract from the overall enjoyment.",
            "'The Lost Chronicles' impresses with strong character development and engaging prose, but the predictable story and rushed resolution make it less impactful.",
            "The HyperTech smartwatch offers great features and sleek design, yet its poor battery life and sluggish interface hold it back from being exceptional.",
            "'Fantasy Quest 3' boasts stunning graphics and an immersive world, but its repetitive main storyline and clunky combat system dampen the experience.",
            "The Oceanview Hotel features beautiful views and spacious rooms with a welcoming staff, though room cleanliness and street noise issues reduce its appeal.",
            "Zen Flow’s yoga class is well-structured and led by a knowledgeable instructor, but large class sizes and poor temperature control can be problematic.",
            "Echoing Waves’ album is filled with innovative sounds and strong vocals, but its lack of cohesion and out-of-place tracks affect the overall flow.",
            "'Advanced Photography Techniques' provides valuable insights and engaging instruction, but outdated materials and technical issues on the platform are frustrating.",
            "The Vegan Bistro offers creative plant-based dishes and a cozy ambiance, though slow service and some lackluster flavors make it a mixed dining experience.",

            "الفيلم الجديد الذي شاهدته يضم مشاهد بصرية رائعة وأداءً تمثيليًا جيدًا، لكن الحبكة كانت ضعيفة والنهاية لم تكن مرضية.",
            "الكتاب الذي قرأته يمتاز بأسلوب كتابة جذاب وبناء شخصية مميز، لكن الحبكة كانت متوقعة للغاية والنهاية جاءت بشكل مستعجل.",
            "المنتجع الذي زُرته يقدم خدمات ممتازة وأجواء هادئة، ولكن النظافة في بعض الأماكن كانت غير مرضية وكانت بعض المرافق بحاجة للصيانة.",
            "البرنامج التعليمي عبر الإنترنت يقدم محتوى قيمًا ومعلمًا مميزًا، لكن الجودة التقنية للموقع والمحتوى المقدم كانت بحاجة لتحسينات.",
            "الساعة الذكية التي اشتريتها تتمتع بميزات متعددة وتصميم عصري، لكن عمر البطارية قصير والأداء في بعض الأحيان يكون بطيئًا.",
            "المطعم الجديد الذي جربته يقدم أطباقًا مبتكرة وطعمًا لذيذًا، ولكن الخدمة كانت بطيئة وبعض الأطباق لم تكن كما توقعت.",
            "دورة اليوغا التي حضرتها كانت موجهة بشكل جيد والمدرب كان محترفًا، لكن حجم المجموعة كان كبيرًا مما قلل من جودة التفاعل الشخصي.",
            "الحديقة العامة التي زرتها تتمتع بمناظر طبيعية جميلة ومساحات خضراء واسعة، لكن بعض المرافق كانت متهالكة والنظافة بحاجة لتحسين.",
            "الاستوديو الفني الذي شاركت فيه يوفر معدات حديثة ومعلمًا خبيرًا، لكن الأوقات المتاحة كانت محدودة وأسعار الحصص مرتفعة.",
            "المنتج الجديد الذي اشتريته يقدم أداءً جيدًا ونتائج مرضية، لكن التوجيهات كانت غير واضحة والتجميع كان صعبًا بعض الشيء.",
            )

